require "test/unit"
require "fileutils"

class TestHoeBundler < Test::Unit::TestCase
  def teardown
    system "git checkout -f test/fixture_project/Gemfile"
  end

  def test_output
    gemfile = nil
    Dir.chdir(File.join(File.dirname(__FILE__), "fixture_project")) do
      FileUtils.rm_f "Gemfile"
      begin
        system "rake bundler:gemfile"
        gemfile = File.read "Gemfile"
      end
    end

    assert_match %r{^# -\*- ruby -\*-$}, gemfile
    assert_match %r{^# DO NOT EDIT THIS FILE. Instead, edit Rakefile, and run `rake bundler:gemfile`.}, gemfile
    assert_match %r{^source :rubygems$}, gemfile
    assert_match %r{^gem "xxx", ">=0"$}, gemfile
    assert_match %r{^gem "yyy", ">=0"$}, gemfile
    assert_match %r{^gem "zzz", "<1.5.0"$}, gemfile
    assert_match %r{^gem "aaa", ">=0", :group => \[:development, :test\]$}, gemfile
    assert_match %r{^gem "bbb", ">=2.2.0", :group => \[:development, :test\]$}, gemfile
    assert_match %r{^gem "ccc", ">=0", :group => \[:development, :test\]$}, gemfile
    assert_match %r{^gem "hoe", "(>=)|(~>)(\d\.\d)|(\.\d)", :group => \[:development, :test\]$}, gemfile
    
    assert_match %r{^# vim: syntax=ruby$}, gemfile
  end

  def test_source_symbol_option
    gemfile = nil
    Dir.chdir(File.join(File.dirname(__FILE__), "fixture_project")) do
      FileUtils.rm_f "Gemfile"
      begin
        system "rake bundler:gemfile[gemcutter]"
        gemfile = File.read "Gemfile"
      end
    end
    assert_match %r{^source \:gemcutter$}, gemfile
  end

  def test_source_http_option
    gemfile = nil
    Dir.chdir(File.join(File.dirname(__FILE__), "fixture_project")) do
      FileUtils.rm_f "Gemfile"
      begin
        system "rake bundler:gemfile[http://gems.github.com]"
        gemfile = File.read "Gemfile"
      end
    end
    assert_match %r{^source "http:\/\/gems\.github\.com"$}, gemfile
  end

  def test_gemspec_option
    gemfile = nil
    Dir.chdir(File.join(File.dirname(__FILE__), "fixture_project")) do
      FileUtils.rm_f "Gemfile"
      begin
        system "rake bundler:gemfile[rubygems,true]"
        gemfile = File.read "Gemfile"
      end
    end
    assert_match %r{^source \:rubygems$}, gemfile
    assert_match %r{^gemspec$}, gemfile
  end

  def test_source_http_and_gemspec_option
    gemfile = nil
    Dir.chdir(File.join(File.dirname(__FILE__), "fixture_project")) do
      FileUtils.rm_f "Gemfile"
      begin
        system "rake bundler:gemfile[http://gems.github.com,true]"
        gemfile = File.read "Gemfile"
      end
    end
    assert_match %r{^source "http:\/\/gems\.github\.com"$}, gemfile
    assert_match %r{^gemspec$}, gemfile
  end
end
